# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runbook < Formula
  desc "Executable runbooks as code — documentation and automation in a single file format"
  homepage "https://github.com/runbookdev/runbook"
  version "0.1.0-beta.0"
  license "Apache-2.0"

  depends_on "sqlite" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runbookdev/runbook/releases/download/v0.1.0-beta.0/runbook_0.1.0-beta.0_darwin_amd64.tar.gz"
      sha256 "b96781bfb29e499eb8ced3b2a041e7e9e6ff3bf696ef942f4ddde1a540f3f5f1"

      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runbookdev/runbook/releases/download/v0.1.0-beta.0/runbook_0.1.0-beta.0_darwin_arm64.tar.gz"
      sha256 "42d5ee6bc5631a6c476d0f477812fbcbd80b2a99d2b26ba479a1e45c76221ccb"

      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbookdev/runbook/releases/download/v0.1.0-beta.0/runbook_0.1.0-beta.0_linux_amd64.tar.gz"
      sha256 "c9e11b5647b669d9a512c6e9364d991441d9daabe715c524f43c770d0c49f452"
      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbookdev/runbook/releases/download/v0.1.0-beta.0/runbook_0.1.0-beta.0_linux_arm64.tar.gz"
      sha256 "baa93f6015c3bc615737e062f625208b20b9b55da02d76d4fa76742050582989"
      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runbook version")
  end
end
