# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runbook < Formula
  desc "Executable runbooks as code — documentation and automation in a single file format"
  homepage "https://github.com/runbookdev/runbook"
  version "0.3.0"
  license "Apache-2.0"

  depends_on "sqlite" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/runbookdev/runbook/releases/download/v0.3.0/runbook_0.3.0_darwin_amd64.tar.gz"
      sha256 "62f0004ff123f39fd66d6fbc0d5e2bc5328d682da36118f07f51dead0f78b1ea"

      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/runbookdev/runbook/releases/download/v0.3.0/runbook_0.3.0_darwin_arm64.tar.gz"
      sha256 "cf75243860b12514ffbefe88505125a2e8fd08e4e5fe4ce05f7ce995145efeb4"

      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbookdev/runbook/releases/download/v0.3.0/runbook_0.3.0_linux_amd64.tar.gz"
      sha256 "02d3657363173d6f9e53fb6eb8c53968f52f3f536cb1e9087f52f4bc4fc1802c"
      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/runbookdev/runbook/releases/download/v0.3.0/runbook_0.3.0_linux_arm64.tar.gz"
      sha256 "c1fa77e31e12c32edd16e50eb6da0beae124b6cf5e807b52c9bd9ef8ad321a1a"
      define_method(:install) do
        bin.install "runbook"
        prefix.install Dir["templates"]
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runbook version")
  end
end
